---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: odfe-kibana
server.host: "0"
elasticsearch.url: http://odfe-node1:9200
# xpack.monitoring.ui.container.elasticsearch.enabled: true
